/**
 * TypeScript Types for Echo
 *
 * Auto-generated by Claudery Blueprint Generator
 */

// ============================================
// USER & AUTH
// ============================================

export interface User {
  id: string;
  email: string;
  username?: string;
  displayName?: string;
  avatarUrl?: string;
  role: "user" | "admin";
  createdAt: Date;
  updatedAt: Date;
}

export interface Profile {
  id: string;
  username?: string;
  displayName?: string;
  avatarUrl?: string;
  bio?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Session {
  user: User;
  accessToken: string;
  expiresAt: Date;
}

// ============================================
// ENTITIES
// ============================================

export interface Build {
  id: string;
  userId: string;
  id: string;
  created_at: Date;
  updated_at: Date;
  user_id: string;
  version: string;
  createdAt: Date;
  updatedAt: Date;
}

export type BuildCreateInput = Omit<Build, "id" | "userId" | "createdAt" | "updatedAt">;
export type BuildUpdateInput = Partial<BuildCreateInput>;

export interface Signal {
  id: string;
  userId: string;
  id: string;
  created_at: Date;
  updated_at: Date;
  user_id: string;
  type: string;
  createdAt: Date;
  updatedAt: Date;
}

export type SignalCreateInput = Omit<Signal, "id" | "userId" | "createdAt" | "updatedAt">;
export type SignalUpdateInput = Partial<SignalCreateInput>;

export interface Private {
  id: string;
  userId: string;
  id: string;
  created_at: Date;
  updated_at: Date;
  user_id: string;
  type: string;
  createdAt: Date;
  updatedAt: Date;
}

export type PrivateCreateInput = Omit<Private, "id" | "userId" | "createdAt" | "updatedAt">;
export type PrivateUpdateInput = Partial<PrivateCreateInput>;

export interface Privacy {
  id: string;
  userId: string;
  id: string;
  created_at: Date;
  updated_at: Date;
  user_id: string;
  createdAt: Date;
  updatedAt: Date;
}

export type PrivacyCreateInput = Omit<Privacy, "id" | "userId" | "createdAt" | "updatedAt">;
export type PrivacyUpdateInput = Partial<PrivacyCreateInput>;

export interface Key {
  id: string;
  userId: string;
  id: string;
  created_at: Date;
  updated_at: Date;
  user_id: string;
  type: string;
  createdAt: Date;
  updatedAt: Date;
}

export type KeyCreateInput = Omit<Key, "id" | "userId" | "createdAt" | "updatedAt">;
export type KeyUpdateInput = Partial<KeyCreateInput>;

export interface End {
  id: string;
  userId: string;
  id: string;
  created_at: Date;
  updated_at: Date;
  user_id: string;
  type: string;
  createdAt: Date;
  updatedAt: Date;
}

export type EndCreateInput = Omit<End, "id" | "userId" | "createdAt" | "updatedAt">;
export type EndUpdateInput = Partial<EndCreateInput>;

export interface Messaging {
  id: string;
  userId: string;
  id: string;
  created_at: Date;
  updated_at: Date;
  user_id: string;
  type: string;
  createdAt: Date;
  updatedAt: Date;
}

export type MessagingCreateInput = Omit<Messaging, "id" | "userId" | "createdAt" | "updatedAt">;
export type MessagingUpdateInput = Partial<MessagingCreateInput>;

export interface Voice {
  id: string;
  userId: string;
  id: string;
  created_at: Date;
  updated_at: Date;
  user_id: string;
  type: string;
  createdAt: Date;
  updatedAt: Date;
}

export type VoiceCreateInput = Omit<Voice, "id" | "userId" | "createdAt" | "updatedAt">;
export type VoiceUpdateInput = Partial<VoiceCreateInput>;

// ============================================
// API RESPONSES
// ============================================

export interface ApiResponse<T> {
  data?: T;
  error?: {
    code: string;
    message: string;
    details?: unknown;
  };
}

export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    total: number;
    limit: number;
    offset: number;
    hasMore: boolean;
  };
}

// ============================================
// COMMON TYPES
// ============================================

export type SortOrder = "asc" | "desc";

export interface SortOptions {
  field: string;
  order: SortOrder;
}

export interface FilterOptions {
  search?: string;
  status?: string;
  dateFrom?: Date;
  dateTo?: Date;
}

export interface QueryOptions {
  limit?: number;
  offset?: number;
  sort?: SortOptions;
  filters?: FilterOptions;
}

// ============================================
// FORM TYPES
// ============================================

export interface FormState<T> {
  values: T;
  errors: Partial<Record<keyof T, string>>;
  touched: Partial<Record<keyof T, boolean>>;
  isSubmitting: boolean;
  isValid: boolean;
}

// ============================================
// UTILITY TYPES
// ============================================

export type WithId<T> = T & { id: string };
export type WithTimestamps<T> = T & { createdAt: Date; updatedAt: Date };
export type Nullable<T> = T | null;
export type Optional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;
